"""
Django settings for amazon_web project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xtm!-l@k&h2%jz-7&o3g8oe!3sxkm%d$ug$=rcz6_$$veu9^=6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'phone_field',
    'ckeditor',
    'sweetify',
    "django_celery_results",
    'django_celery_beat',
    'crispy_forms',
    "crispy_bootstrap4",
    'django_filters',
    'cities_light',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amazon_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.views.category_details',
                'shop.views.get_special_product',
                'cart.context_processor.cart_detail',
                'shop.views.get_special',
                'shop.views.get_recent_product',
            ],
        },
    },
]

WSGI_APPLICATION = 'amazon_web.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = 'bootstrap4'
#CELERY_TASK_ALWAYS_EAGER = True

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}






EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'edehchetachukwu23@gmail.com'
EMAIL_HOST_PASSWORD = 'qvpr bstz gamg usnr'




#CSRF_TRUSTED_ORIGINS = ['https://be1c-105-113-10-88.ngrok-free.app']
#CSRF_COOKIE_SECURE = True



# Celery settings
# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379'

CELERY_RESULT_BACKEND = 'redis://localhost:6379'
#CELERY_ACCEPT_CONTENT = ['json']
#CELERY_TASK_SERIALIZER = 'json'
#CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

STRIPE_PUBLISHABLE_KEY = 'pk_test_51LyX9GFNcFvRpb8McfplqR6jyX5JXTdmmNV3F58KZMAKBoqjGsGJzI0o7uTNREbQNgifTFvMpWnpPQ1Lo2lryc4x00g2eF6QmZ'
STRIPE_API_VERSION = '2022-08-01'
STRIPE_SECRET_KEY = 'sk_test_51LyX9GFNcFvRpb8MuYbTkVoFnZAg8PHcv6YEyVICzC01qMTqFtqAI4EFGkC0GZnoeRNKvysAfoSObUV3KUHtHyxs00v6vEWIoR'
STRIPE_WEBHOOK_SECRET = 'whsec_04ec1f42df7f0a4730a80da954022f4ee78e7689cb8103a2036e03e7195c956f'

PAYSTACK_SECRET_KEY = 'sk_test_b049f46a4558b137aa2e10f6d3f36a5d59228d72'
PAYSTACK_PUBLIC_KEY = 'pk_test_838fbd12bc4a400dfc1edfd958527944cd1d4d38'

FLUTTERWAVE_SECRET_KEY = 'FLWSECK_TEST-47c46a8e706e38f03b9f643358303dfe-X'

MONNIFY_SECRET_KEY = '79LU3ST4BDGSNZTE8FUNQQ45YJENDEWL'
MONNIFY_API_KEY = 'MK_TEST_A22XGSQHDT'
MONNIFY_ENCODED = 'TUtfVEVTVF9BMjJYR1NRSERUOjc5TFUzU1Q0QkRHU05aVEU4RlVOUVE0NVlKRU5ERVdM'

PAYPAL_CLIENT_ID = 'AQFhHDe4duWXeHFqgkf-_W5agFeA1YUdsKAz3ygNVm-2U6zdhAGslKvhjS8tHKzTyMYN5WPlUPEAuBXM'
PAYPAL_SECRET = 'EJeH8EaN9gJax7oly6X9rhh2BnnlESsO42y4J00GRh8Y4VQpZinOyddYgVXvd5D-DrBLiYBEaHLjHNv1'

OPAY_SECRET_KEY = 'OPAYPRV17228279012780.12922691986850265'
OPAY_PUBLIC_KEY = 'OPAYPUB17228279012780.05761314877501522'
OPAY_MERCHANT_ID = '281824080552441'

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
