# Generated by Django 5.0.4 on 2024-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='polartity',
            field=models.BooleanField(default=False),
        ),
    ]
